### PR TITLE
added posts.update and some rspec change

### PR DESCRIPTION
**Pull request by cfiorini**
I have added posts.update that is still in beta on Disqus API documentation.
Also i changed something about rspec to get all pass using a real disqus account.

### CODE REVIEW

**Comment by einzige** [comment]
https://github.com/toptal/disqus_api/pull/11

**Comment by einzige** [comment]
sorry for miscommunication :)

**Comment by einzige** [comment]
thank you @cfiorini , appreciate your help, merged!

**Comment by cfiorini** [comment]
@einzige thanks to you to merge it :)

**Pull request merged**
